Добавляет 2 функции по поиску случайных чисел
htmlacademy-javascript/843811-keksobooking-25 pull request #2
Opened 2022-02-22 09:10 UTC by kein7z

2022-02-22 16:52 UTC, Dima-Dim requested changes
Поправить ошибки на которые указывает линтер.

2022-02-22 16:52 UTC, Dima-Dim commented on index.html
> +            <input type="checkbox" name="features" value="dishwasher" id="filter-dishwasher"
В задании нет ничего про редактировании этих участков разметки.

2022-02-22 16:52 UTC, Dima-Dim commented on js/main.js
> +    return 'invalid input value'
Ошибку лучше вывести с помощью console.error();

2022-02-24 07:14 UTC, kein7z commented
Добавил console.error(); , но линтер ругается на то, что в коде есть вывод в консоль, так же вернул изменения в разметке, их vs code внес автоматически

2022-02-24 08:18 UTC, Dima-Dim approved these changes

2022-02-24 08:18 UTC, merged